version: 1.0.{build}

install:
  - ps: wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-win32-x86.zip -OutFile cmake.zip
  - cmd: echo "Unzipping cmake..."
  - cmd: 7z x cmake.zip -o"C:\Program Files (x86)\" -y > nul
  - cmd: set PATH=%PATH:CMake 2.8\bin=%;C:\Program Files (x86)\cmake-3.0.2-win32-x86\bin
  - cmd: cmake --version
  - cmd: echo "Downloading biicode..."
  - ps: wget http://www.biicode.com/downloads/latest/win -OutFile bii-win.exe
  - cmd: bii-win.exe /VERYSILENT
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\BiiCode\bii
  - cmd: bii -v
  - cmd: del bii-win.exe
  - cmd: del cmake.zip

before_build:
  - cmd: cd \
  - cmd: bii init %project_name%
  - cmd: cd %project_name%
  - cmd: bii new %block_user%/%block_name%
    # copy files and folders
  - cmd: xcopy "%APPVEYOR_BUILD_FOLDER%" blocks\%block_user%\%block_name%\ /e
  - cmd: bii cpp:configure -G "Visual Studio 12"

build_script:
  - cmd: bii cpp:build

test_script:
  - cmd: cd bin
  - cmd: amalulla_cpp-expression-parser_test-shunting-yard.exe

environment:
  project_name:
    "myproject"
  block_user:
    "amalulla"
  block_name:
    "cpp-expression-parser"
